### ISSUE TITLE
No R Attributes in TMATS related to the 429 Bus

### ISSUE THREAD

**Issue by dglowe** [atac/SyntheticData#5]
Likely not a huge deal, but the B-x\DLN for A429InChan1 doesn't have a Recorder-Reproducer Attribute to which it maps.

**Comment by bbaggerman** [comment]
"R-1\CDLN-4:A429InChan1;" connects to "B-2\DLN:A429InChan1;". Looks OK to me.

**Comment by dglowe** [comment]
Sorry my bad. You're as good at finding things I'm missing as my wife. (Its a complement. She's a wizard at finding things). For the record:

![image](https://user-images.githubusercontent.com/42627003/156436494-dd27b6c0-43a0-44f9-beb6-c02640408b31.png)

Notepad chose not to find "A429InChan1". I found it in Notepad++ after reading your comment. Closing issue
